### ISSUE TITLE
$_GET didn't work! Cannot handle an error

### ISSUE THREAD

**Issue by srikresna** [srikresna/final-project-library#5]
url = http://localhost/db/public/patron/reservation?error=date_taken
![Untitled](https://github.com/srikresna/yws/assets/28501206/f885df35-b1d8-41e0-89bd-82e31e4f3f64)

always return GAONO!

**Comment by G4CENeiz** [comment]
anak siapa "assigned G4CENeiz"

**Comment by srikresna** [comment]
> anak siapa "assigned G4CENeiz"

ayo cepatt

**Comment by G4CENeiz** [comment]
Dah dihapus males
